### ISSUE TITLE
Comments on security consideration

### ISSUE THREAD

**Issue by itchyny** [bauerd/jqrp#2]
Hi, gojq author here.

> jqrp uses gojq with all its compiler options disabled. Query evaluation in jqrp is likely not Turing-complete.

Even if you disable all the gojq compiler options, the jq language itself is Turing-complete; it can emulate the state by objects and repeat update procedures by recursion. Also, there are simple queries which do not terminate; `repeat(0)` and `range(infinite)`. In order to limit the execution time, use `context.Context` with `code.RunWithContext`.

**Comment by bauerd** [comment]
Hi and thank you, I was not aware of jq being Turing-complete at all! I will amend the README accordingly.
Just as I wasn't aware of `code.RunWithContext` :-)

This was a weekend project to get my feet wet with Go, the README should probably reflect that this is by no means production-grade software.

Out of curiosity, how did you stumble upon this repo?

Cheers and have a good Wednesday!

**Comment by itchyny** [comment]
Okay, I understand the project state. I just randomly pick up my library importers and investigate the usage to improve gojq document. Good luck.
